import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const schema = {
  User: {
    id: String,
    email: String,
    password: String,
    firstName: String,
    lastName: String,
    gender: String,
    dateOfBirth: DateTime,
    createdAt: DateTime,
    updatedAt: DateTime,
    profile: Profile,
    membership: Membership,
  },
  Profile: {
    id: String,
    userId: String,
    height: String,
    weight: String,
    maritalStatus: String,
    religion: String,
    caste: String,
    motherTongue: String,
    education: String,
    occupation: String,
    annualIncome: String,
    workLocation: String,
    fatherName: String,
    fatherOccupation: String,
    motherName: String,
    motherOccupation: String,
    siblings: String,
    familyType: String,
    horoscope: Horoscope,
    preferences: Preferences,
    photos: Photo[],
    isVerified: Boolean,
    createdAt: DateTime,
    updatedAt: DateTime,
  },
  Horoscope: {
    id: String,
    profileId: String,
    dateOfBirth: DateTime,
    timeOfBirth: String,
    placeOfBirth: String,
    rashi: String,
    nakshatra: String,
    gotra: String,
    createdAt: DateTime,
    updatedAt: DateTime,
  },
  Preferences: {
    id: String,
    profileId: String,
    ageRange: String,
    height: String,
    maritalStatus: String,
    religion: String,
    education: String,
    location: String,
    createdAt: DateTime,
    updatedAt: DateTime,
  },
  Photo: {
    id: String,
    profileId: String,
    url: String,
    isProfilePhoto: Boolean,
    isVerified: Boolean,
    createdAt: DateTime,
    updatedAt: DateTime,
  },
  Membership: {
    id: String,
    userId: String,
    type: String, // 'free' or 'premium'
    startDate: DateTime,
    endDate: DateTime,
    features: String[], // Array of enabled features
    isActive: Boolean,
    createdAt: DateTime,
    updatedAt: DateTime,
  },
  Message: {
    id: String,
    senderId: String,
    receiverId: String,
    content: String,
    isRead: Boolean,
    createdAt: DateTime,
    updatedAt: DateTime,
  },
  Interest: {
    id: String,
    senderId: String,
    receiverId: String,
    status: String, // 'pending', 'accepted', 'rejected'
    createdAt: DateTime,
    updatedAt: DateTime,
  },
}; 